#!/bin/sh
set -eu

input=$(cat)

if [ -z "$input" ]; then
  exit 0
fi

escaped=$(printf '%s' "$input" | awk 'BEGIN {ORS=""; first=1}
{
  line = $0
  gsub(/\\/, "\\\\", line)
  gsub(/"/, "\\\"", line)
  gsub(/\t/, "\\t", line)
  gsub(/\r/, "\\r", line)
  if (!first) printf "\\n"
  first = 0
  printf "%s", line
}
')

printf '%s\n' '{"type":"message","source":"user","payload":{"text":"'"$escaped"'"}}'
